language: objective-c
osx_image: xcode8.3
xcode_project: CDGSwiftIntExtension.xcodeproj
xcode_scheme: CDGSwiftIntExtension
xcode_sdk: iphonesimulator10.3

script:
    - xcodebuild clean build -sdk iphonesimulator -project CDGSwiftIntExtension.xcodeproj -scheme CDGSwiftIntExtension CODE_SIGNING_REQUIRED=NO
